nosana:
  description: Nosana-Node Pipeline

global:
 # docker pull 
  image: registry.hub.docker.com/library/solanalabs/rust:latest

  trigger:
    branch:
      - master

jobs:
  - name: Hello World Solana
    commands:
      - ls
      - npm install
      - npm run build:program-rust
      