nosana:
  description: Nosana-Node Pipeline

global:
 # projectserum/build:v0.26.0
  image: registry.hub.docker.com/projectserum/build:v0.26.0

  trigger:
    branch:
      - master

jobs:
  - name: Hello World Solana
    commands:
      - ls
      - npm install
      - npm run build:program-rust
      - ls dist/progam
    artifacts:
      - name: dist
        path: progam/dist/
    
  - name: Test Solana
    commands:
      - ls
      - npm run test:program-rust
    resources:
      - name: dist
        path: ./
    
    
      